name: OSV-Scanner PR Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]

permissions:
  actions: write
  security-events: write
  contents: write

jobs:
  scan-pr:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.2.3"
